config/routes.rb
Rails.application.routes.draw do
  # sign_up, sign_in, sign out, etc.
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resource :home, only: %i[ index ]

  # /service_providers
  resources :service_providers do
    resources :service_offers, controller: "service_providers/service_offers"
    resources :user_service_provider_accesses, as: :accesses
    resources :quote_requests, only: %i[ show index ]
    resource :quote_history, controller: "service_providers/quote_history", only: %i[ index ]
  end

  resources :service_quotes, only: %i[ new create destroy index ]
  resources :services, only: %i[ new create ]

  # /users
  resources :users do
    # users form actions #? turn into resource somehow?
    post :is_service_provider, on: :collection
    post :is_not_service_provider, on: :collection
  end

  resources :user_service_provider_accesses
  #?
  scope :user do
    get :service_providers, controller: :users, action: :service_providers, as: :user_service_providers
  end

  resources :service_requests do  # for when a client interacts with a service_request they have made
    collection do
      post :use_new_city, as: :use_new_city
      post :use_existing_city, as: :use_existing_city
    end
  end

  resource :service_request_coordinate_choice, only: %i[ new ]
  resource :service_form_cancellation, only: %i[ new ]

  resource :coordinate_city_choice, only: %i[ new ]

  # when service providers search for service requests that they might be able to fulfill
  resources :service_request_searches, only: %i[ new ]

  # there are many possible service providders for which a user might want to access their portals, so service provider portal is a plural resource
  resources :service_provider_portals, only: %i[ show ]
  # the client portal always redirects to the user's client account, so it is a singular resource
  resource :client_portal, only: [ :show ]

  # /clients
  resources :clients do
    resources :quote_requests, only: %i[ new create index ]
    resource :coordinate, only: %i[ new create edit update destroy ], controller: "clients/coordinates"
    resource :coordinate_edit_cancellation, only: %i[ new ], controller: "clients/coordinate_edit_cancellations"
=begin
    member do
      #! to be obsoleted x3
      get :edit_coordinate, to: "clients#edit_coordinate", as: :edit_coordinate
      get :cancel_edit_coordinate, to: "clients#cancel_edit_coordinate", as: :cancel_edit_coordinate
      patch :edit_coordinate, to: "clients#update_coordinate", as: :update_coordinate
    end
=end
  end

  namespace :client do
    resource :coordinate, only: %i[new create edit update destroy]
    resources :service_request_activations, only: %i[ new destroy ]
  end

  resources :service_provider_searches, only: %i[ new create ]

  #! to be obsoleted
  scope module: :clients do
    get "client/service_request/:id", to: "service_requests#show", as: :client_service_request
    get "client/service_request/:id/service_providers", to: "service_requests#find_providers", as: :find_service_request_providers
    post "client/service_request/:id/cancel", to: "service_requests#cancel", as: :cancel_service_request
    post "client/service_request/:id/activate", to: "service_requests#activate", as: :activate_service_request
  end

  # /service_providers
  scope :service_provider do
    get :browse_service_requests, to: "service_providers#browse_service_requests", as: :browse_service_requests_as_service_provider
    get :quote_history, to: "service_providers#quote_history", as: :service_provider_quote_history
  end

  # /cities
  resources :cities

  # /coordinates
  #! this probably shouldn't exist, should be through the other resources? or maybe only new/create
  resources :coordinates do
    # coordinate form actions
    # probably should use a resource, coordinate_city_choice or sth
    # /coordinates/use_new_city
    post :use_new_city, on: :collection
    # /coordinates/use_existing_city
    post :use_existing_city, on: :collection
  end

  # /service_categories
  resources :service_categories do
    member do
      # picker actions
      # todo how to turn into resource? => service_category_choice
      get :pick, as: :pick
    end
    # /service_categories/[:service_category_id]/services
    resources :services, only: %i[ index ]
  end

  # /transportation_services
  # todo
  # resources :transportation_services

  root "home#index"

  # Developement resources
  if Rails.env.development?
    resources :design_systems, only: [ :index ]
  end
end

app/models/service_category.rb
# t.string :label
# t.string :description
# t.string :icon_path
# t.references :parent, class_name: "ServiceCategory", null: true, foreign_key: true      # top level categories have nil parent
class ServiceCategory < ApplicationRecord
  belongs_to :parent, class_name: "ServiceCategory", optional: true
  has_many :subcategories, class_name: "ServiceCategory", inverse_of: :parent, foreign_key: :parent_id
  has_many :services

  scope :top_level, -> { where(parent: nil) }

  validates :label, uniqueness: true

  # find all parents + self, in top-down order, to display as breadcrumbs
  def breadcrumbs
    current = self
    crumbs = []
    while current 
      crumbs.unshift(current)
      current = current.parent
    end
    crumbs
  end
end

app/controllers/service_categories_controller.rb
class ServiceCategoriesController < ApplicationController
    def pick
        # picked category
        @category = ServiceCategory.find_by_id(params[:id])
        # categories whose parent is @category
        @subcategories = ServiceCategory.where(parent: @category)
        
        respond_to do |format|
            # if there exists a category with ID params[:id]
            if @category 
                format.html { render partial: 'pick', locals: { category: @category, carousel_categories: @subcategories, breadcrumbs_categories: @category.breadcrumbs, selected_category_id: @category.id }, status: :ok }
                format.turbo_stream { render 'pick', locals: { service_category: @category }}
            # else, if ID is 0, code for "reset" picker so show top-level categories, empty breadcrumbs
            elsif params[:id] == 0.to_s
                format.html { render partial: 'pick', locals: { carousel_categories: ServiceCategory.top_level }, status: :ok}
                format.turbo_stream { render 'pick', locals: { service_category: nil }}
            # invalid category_id
            else 
                throw "invalid category_id: #{@category.inspect}"
                format.html { render partial: 'pick', locals: {}, status: :unprocessable_entity }
                format.turbo_stream { render 'pick', locals: { service_category: nil }, status: :unprocessable_entity }
            end
        
        end
    end

    private
    def service_category_params

    end
end

app/helpers/service_categories_helper.rb
module ServiceCategoriesHelper
end

app/views/service_categories/_breadcrumbs.html.erb
<%= turbo_frame_tag "service-category-picker__breadcrumbs" do %>
    <%= content_tag :div, class: "service-category-picker__breadcrumbs" do %>
        <%= content_tag :span do %>
            <%= link_to t('models.service_category.list_title'), pick_service_category_path(0.to_i), data: { turbo_stream: true }, class: "button" %>
            <% breadcrumbs_categories ||= [] %>
            <% breadcrumbs_categories.each_with_index do |category, i| %>
                <%= content_tag :span, class: "breadcrumb-link" do %>
                    &gt;
                <% end %>
                <%= link_to pick_service_category_path(category.id), class: "button", data: { turbo_stream: true } do %>
                    <%= render 'service_categories/service_category', service_category: category %>
                <% end %>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/service_categories/_carousel.html.erb
<%= turbo_frame_tag "service-category-picker__carousel" do %>
    <%# if no carousel_categories provided, default to top level service categories %>
    <% carousel_categories ||= ServiceCategory.top_level %>
    <%= content_tag :div, class: "carousel carousel--service-categories" do %>
        <% carousel_categories.each do |category| %>
            <%= link_to pick_service_category_path(id: category.id), class: "button", data: { turbo_stream: true } do %>
                <%= render 'service_categories/service_category', service_category: category %>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/service_categories/_pick.html.erb
<%= turbo_frame_tag "service-category-picker" do %>
    <%= content_tag :div, class: "service-category-picker" do %>
        <%= render partial: "service_categories/breadcrumbs", locals: { breadcrumbs_categories: local_assigns[:service_category]&.breadcrumbs || [] } %>
        <%= render partial: "service_categories/carousel", locals: { carousel_categories: local_assigns[:service_category]&.subcategories || ServiceCategory.top_level } %>
    <% end %>
<% end %>

app/views/service_categories/_service_category.html.erb
<%= content_tag :div, class: "service-category" do %>
    <%= content_tag :div, class: "service-category__label" do %>
        <%= service_category.label %>
    <% end %>
    <%= content_tag :div, class: "service-category__icon" do %>
        <%= image_tag service_category.icon_path, size: "16" if service_category.icon_path %>
    <% end %>
<% end %>

app/views/service_categories/pick.turbo_stream.erb
<%# replace the shown subcategories in the button carousel by the picked category's own subcategories, default to show top-level categories %>
<%= turbo_stream.replace "service-category-picker__carousel" do %>
    <%= render partial: 'service_categories/carousel', locals: { carousel_categories: service_category ? service_category.subcategories : ServiceCategory.top_level } %>
<% end %>

<%# update the breadcrumbs showing the currently picked subcategory and each of its parent categories %>
<%= turbo_stream.replace "service-category-picker__breadcrumbs" do %>
    <%= render partial: 'service_categories/breadcrumbs', locals: { breadcrumbs_categories: service_category ? service_category.breadcrumbs : [] } %>
<% end %>

<%# only show the "service" label if there are any services to show %>
<%= turbo_stream.update_all "#service-picker-select label" do %>
    <% if service_category && service_category.services.count > 0 %>
        <%= tag.label t('models.service.model_name') %>
    <% end %>
<% end %>

<%# update the service select options to show the picked category's services %>
<%= turbo_stream.update_all "#service-picker-select select" do %>
    <%= service_picker_services_select_options(service_category) %>
<% end %>

<%# keep track of the service category in a hidden form, in case the service needs to be created %>
<%= turbo_stream.update_input "service-picker-category", service_category&.id || 0 %>