config/routes.rb
Rails.application.routes.draw do
  # sign_up, sign_in, sign out, etc.
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resource :home, only: %i[ index ]

  # /service_providers
  resources :service_providers do
    resources :service_offers, controller: "service_providers/service_offers"
    resources :user_service_provider_accesses, as: :accesses
    resources :quote_requests, only: %i[ show index ]
    resource :quote_history, controller: "service_providers/quote_history", only: %i[ index ]
  end

  resources :service_quotes, only: %i[ new create destroy index ]
  resources :services, only: %i[ new create ]

  # /users
  resources :users do
    # users form actions #? turn into resource somehow?
    post :is_service_provider, on: :collection
    post :is_not_service_provider, on: :collection
  end

  resources :user_service_provider_accesses
  #?
  scope :user do
    get :service_providers, controller: :users, action: :service_providers, as: :user_service_providers
  end

  resources :service_requests do  # for when a client interacts with a service_request they have made
    collection do
      post :use_new_city, as: :use_new_city
      post :use_existing_city, as: :use_existing_city
    end
  end

  resource :service_request_coordinate_choice, only: %i[ new ]
  resource :service_form_cancellation, only: %i[ new ]

  resource :coordinate_city_choice, only: %i[ new ]

  # when service providers search for service requests that they might be able to fulfill
  resources :service_request_searches, only: %i[ new ]

  # there are many possible service providders for which a user might want to access their portals, so service provider portal is a plural resource
  resources :service_provider_portals, only: %i[ show ]
  # the client portal always redirects to the user's client account, so it is a singular resource
  resource :client_portal, only: [ :show ]

  # /clients
  resources :clients do
    resources :quote_requests, only: %i[ new create index ]
    resource :coordinate, only: %i[ new create edit update destroy ], controller: "clients/coordinates"
    resource :coordinate_edit_cancellation, only: %i[ new ], controller: "clients/coordinate_edit_cancellations"
=begin
    member do
      #! to be obsoleted x3
      get :edit_coordinate, to: "clients#edit_coordinate", as: :edit_coordinate
      get :cancel_edit_coordinate, to: "clients#cancel_edit_coordinate", as: :cancel_edit_coordinate
      patch :edit_coordinate, to: "clients#update_coordinate", as: :update_coordinate
    end
=end
  end

  namespace :client do
    resource :coordinate, only: %i[new create edit update destroy]
    resources :service_request_activations, only: %i[ new destroy ]
  end

  resources :service_provider_searches, only: %i[ new create ]

  #! to be obsoleted
  scope module: :clients do
    get "client/service_request/:id", to: "service_requests#show", as: :client_service_request
    get "client/service_request/:id/service_providers", to: "service_requests#find_providers", as: :find_service_request_providers
    post "client/service_request/:id/cancel", to: "service_requests#cancel", as: :cancel_service_request
    post "client/service_request/:id/activate", to: "service_requests#activate", as: :activate_service_request
  end

  # /service_providers
  scope :service_provider do
    get :browse_service_requests, to: "service_providers#browse_service_requests", as: :browse_service_requests_as_service_provider
    get :quote_history, to: "service_providers#quote_history", as: :service_provider_quote_history
  end

  # /cities
  resources :cities

  # /coordinates
  #! this probably shouldn't exist, should be through the other resources? or maybe only new/create
  resources :coordinates do
    # coordinate form actions
    # probably should use a resource, coordinate_city_choice or sth
    # /coordinates/use_new_city
    post :use_new_city, on: :collection
    # /coordinates/use_existing_city
    post :use_existing_city, on: :collection
  end

  # /service_categories
  resources :service_categories do
    member do
      # picker actions
      # todo how to turn into resource? => service_category_choice
      get :pick, as: :pick
    end
    # /service_categories/[:service_category_id]/services
    resources :services, only: %i[ index ]
  end

  # /transportation_services
  # todo
  # resources :transportation_services

  root "home#index"

  # Developement resources
  if Rails.env.development?
    resources :design_systems, only: [ :index ]
  end
end

app/models/service_provider.rb
# t.string :name
# t.string :description
# t.string :schedule
# t.string :phone_number
# t.string :email_address
# t.references :coordinate, null: true, foreign_key: true
class ServiceProvider < ApplicationRecord
    has_many :user_service_provider_accesses
    has_many :users, through: :user_service_provider_accesses
    has_many :service_offers
    has_many :services, through: :service_offers
    has_many :service_quotes
    has_many :service_requests, through: :service_quotes
    belongs_to :coordinate, optional: true

    accepts_nested_attributes_for :coordinate
    
    before_save :destroy_coordinate_if_empty

    def destroy_coordinate_if_empty
        if coordinate && coordinate.empty?
            old_coord = coordinate
            self.coordinate_id = nil
            begin
                old_coord.destroy
            rescue ActiveRecord::InvalidForeignKey
                #todo if coordinate has other objects tied to it somehow, their coordinate_id should also be set to nil, but it's edge case with super low priority that has marginal benefits so wtv
            end
        end 
    end

    def active_quotes
        service_quotes.where(status: ServiceQuoteStatus.open)
    end

    def active_accesses
        # accesses are active until they're not - if an "inactive_from" time is specified, access is assumed to be revoked (or role changed)
        user_service_provider_accesses.where(inactive_from: nil)
    end

    def quote_history
        # reverse chronological order
        service_quotes.order(created_at: :desc)
    end
end

app/controllers/service_providers/quote_history_controller.rb
class ServiceQuoteHistoriesController < ApplicationController
    def index 
        set_service_provider
        render "service_quotes/history"
    end

    private 

    def set_service_provider
        @service_provider = params(:id)
    end
end

app/controllers/service_providers/service_offers_controller.rb
class ServiceProviders::ServiceOffersController < ApplicationController
    # called from service_provider/:id/offers
    def index
        set_service_provider
        @service_offers = ServiceOffer.where(service_provider: @service_provider)
    end

    def new
        set_service_provider
        @service_offer = ServiceOffer.new(service_provider_id: @service_provider.id)

    end

    def create
        set_service_provider
        @service_offer = ServiceOffer.new(service_offer_params)
        @service_offer.service_provider = @service_provider

        respond_to do |format|
            if @service_offer.save
            else
                puts @service_offer.errors.full_messages
                format.html { render 'service_providers/portal', status: :unprocessable_entity}
            end
        end
    end

    def update
        set_service_offer
        if @service_offer.update(service_offer_params)

        end
    end

    # for edit, :id is service_offer.id
    def edit
        set_service_offer

    end

    def destroy
        set_service_offer
        @service_offer.destroy

    end

    private
    def set_service_offer
        @service_offer = ServiceOffer.find_by_id(params[:id])
    end

    def set_service_provider
        @service_provider = ServiceProvider.find_by_id(params[:service_provider_id])
    end

    def service_offer_params
        params.require(:service_offer).permit(:service_provider_id, :service_id, :min_price, :description)
    end

    def filepath(view)
        "#{view_root}#{view.to_s}"
    end

    def view_root
        "service_providers/portal/service_offers/"
    end
end

app/controllers/service_providers_controller.rb
class ServiceProvidersController < ApplicationController
    before_action :set_service_provider, only: %i[ show edit destroy update ask_quote service_offers ]
    before_action :set_user, only: %i[ new create updates destroy ]
    before_action :authorize, only: %i[ :portal ]
    # maybe should be moved to another namespace

    def show
    end

    # admin can edit service providers, use turbo to turn the info panel into the service_provider form
    def edit 
        # prepare the coordinate field if it doesn't exist
        @service_provider.coordinate = Coordinate.new if @service_provider.coordinate.nil?
    end 

    def index_for_client
        @service_providers = ServiceProvider.all
    end

    def new
        @service_provider = ServiceProvider.new
        @service_provider.coordinate = Coordinate.new
    end

    def create
        @service_provider = ServiceProvider.new(service_provider_params)

        if @service_provider.save

            # assume whoever created the service provider is the admin, so create the user's access
            if UserServiceProviderAccess.new(user_id: current_user.id, service_provider_id: @service_provider.id, user_role: UserRole.admin, grantor_id: current_user.id, active_from: Time.now)
                redirect_to service_provider_portal_path
            end
            render 'new', status: :unprocessable_entity
        else
            render 'new', status: :unprocessable_entity
        end
    end

    def update

        respond_to do |format|
            if @service_provider.update(service_provider_params)
                format.html { redirect_to service_provider_portal_path(@service_provider) }
                format.turbo_stream
            else
                format.html { redirect_to service_provider_portal_path(@service_provider) }
                puts @service_provider.errors.full_messages
            end
        end
    end

    def destroy
        @service_provider.destroy

        respond_to do |format|
            format.html { redirect_to service_providers_path, notice: I18n.t('models.service_provider.destroy_success') }
            format.turbo_stream
        end
    end

    def browse_service_requests
        
    end

    # actual service_provider params

    #!! ?
    def service_ask_quote
        @service = params(:service_id)
    end
    
    # p2
    def offer_help
        @user = current_user
    end

    private
    def set_user 
        @user = current_user
    end 

    def set_service_provider
        @service_provider = ServiceProvider.find_by_id(params[:id])
    end 

    def set_or_new_service_provider
        unless set_service_provider
            @service_provider = ServiceProvider.new
        end
    end

    def service_provider_params
        params.require(:service_provider).permit(:id, :name, :description, :schedule, :phone_number, :email_address, :coordinate_id, coordinate_attributes: [ :id, :civic_number, :street_name, :door_number, :postal_code, :notes, :city_id, city_attributes: [ :id, :name, :province_code ] ])
    end
end

app/helpers/service_providers_helper.rb
module ServiceProvidersHelper
end

app/views/service_providers/_active_quotes.html.erb
<%= turbo_frame_tag 'active-service-quotes' do %>    
    <% unless service_provider.active_quotes.empty? %>
        <% service_provider.active_quotes.each do |quote| %>
            <%= render quote, can_edit: true, link_to_service_request: true %>
        <% end %>
    <% else %>
        <%= t('feedback.service_provider.no_active_quotes') %>
    <% end %>
<% end %>

app/views/service_providers/_fields.html.erb
<%= form.field :name %>
<%= form.field :description, as: :text %>
<%= form.field :schedule, as: :text %>
<%= form.field :phone_number %>
<%= form.field :email_address %>

<%# optional coordinates %>
<%= content_tag :div, id: "coordinate-form" do %>
    <%= form.fields_for :coordinate do |coordinate_form| %>
        <%= content_tag :div, class: "coordinate-form" do %>
            <%= content_tag :h3, class: "form__header" do %>
                <%= "#{t('models.coordinate.create_title')} (#{t('keywords.optional')})" %>
            <% end %>
            <%= render partial: "coordinates/fields", locals: { form: coordinate_form } %>
        <% end %>
    <% end %>
<% end %>

app/views/service_providers/_form.html.erb
<%= model_form_with model: service_provider, data: { test_id: "service-provider-form"} do |form| %>
    <% if service_provider.errors.any? %>
        <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
                <% service_provider.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= content_tag :div, class: "service-provider-fields" do %>
        <%= render partial: "service_providers/fields", locals: { form: form } %>
        <%# submit button %>
        <%= content_tag :div, class: "actions" do %>
            <% if service_provider.new_record? %>
                <%= form.submit "#{t('models.register')} #{t('models.service_provider.model_name')}" %>
            <% else %>
                <%= form.submit "#{t('models.update')} #{t('models.service_provider.model_name')}" %>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/service_providers/_management_panel.html.erb
<%= turbo_frame_tag 'services' do %>
    <%= @service_provider.services %>
<% end %>
<%= turbo_frame_tag 'user-accesses' do %>
    <%= @service_provider.user_service_provider_accesses%>
<% end %>
<%= turbo_frame_tag 'service-provider-form' do %>
    <%= render 'form', service_provider: @service_provider %>
<% end %>
<%= turbo_frame_tag 'quotes-list' do %>
    <%= link_to t('models.service_provider.quote_history'), service_provider_quote_history_path(@service_provider) %>
<% end %>

app/views/service_providers/_service_provider.html.erb
<%= tag.div class: "service-provider model-widget", id: dom_id(service_provider) do %>
    <%= tag.div service_provider.name, class: "service-provider__name" %>

    <%= tag.div service_provider.phone_number, class: "service-provider__phone-number" %>

    <%= tag.div service_provider.email_address, class: "service-provider__email-address" %>

    <% if local_assigns[:service_offer] %>
        <%= tag.div price_range(service_offer.min_price, service_offer.max_price) %>
    <% end %>

    <%= tag.div class: "actions" do %>
        <% if local_assigns[:can_edit] %>
            <%= link_to t('keywords.edit'), service_provider_portal(service_portal) %>
        <% end %>
        <% if local_assigns[:service_offer] %>
            <%= link_to 'request_quote', 'request_quote_path', class: "button" %>
        <% end %>
    <% end %>
<% end %>

app/views/service_providers/destroy.turbo_stream.erb
<%= turbo_stream.remove @service_provider %>

app/views/service_providers/edit.turbo_stream.erb
<%# turn the "info" panel into a proper form %>
<%= turbo_stream.update "#{dom_id(@service_provider)}-info" do %>
    <%= render partial: "service_providers/form", locals: { service_provider: @service_provider } %>
<% end %>

app/views/service_providers/new.html.erb
<%= content_tag :main, class: "container" do %>
    <%= content_tag :h2 do %>
        <%= t('models.service_provider.create_title') %>
    <% end %>
    <%= turbo_frame_tag @service_provider do %>
        <%= render 'form', service_provider: @service_provider %>  
    <% end %>
<% end %>

app/views/service_providers/portal.html.erb
<%= tag.main class: "portal portal--service-provider", data: { test_id: 'service-provider-portal' } do %>
    <%= tag.h1 @service_provider.name %>
    <%= tag.section class: "card v-flex", data: { test_id: "active-quotes"} do %>
        <%= tag.h3 t('models.service_quote.list_title') %>
        <%= render partial: "service_providers/active_quotes", locals: { service_provider: @service_provider } %>
        <%= tag.div 'service-requests-search' do %>
            <%= link_to t('cta.find_service_requests'), new_service_request_search_path(id: @service_provider.id), class: "button" %>
        <% end %>
    <% end %>

    <%= tag.section class: "card service-provider-info", id: "#{dom_id(@service_provider)}-info", data: { test_id: "info" } do %>
        <%= render "service_providers/portal/info", service_provider: @service_provider %>
    <% end %>

    <%= tag.section data: { test_id: "service-offers" } do %>
        <%= render "service_providers/portal/service_offers", service_provider: @service_provider %>
    <% end %>

    <% if current_user.is_service_provider_admin? @service_provider %>
        <%= render 'service_providers/portal/admin_panel/admin_panel', service_provider: @service_provider %>
    <% end %>
<% end %>

app/views/service_providers/show.html.erb
<%= content_tag :h2, @service_provider.name %>
<%= tag.div class: "card service-provider" do %>
    <%= tag.div class: "binome" do %>
        <%= content_tag :div do %>
            <%= "#{@service_provider.description}" %>
        <% end %>
        <%= tag.div class: "field" do %>
            <%= tag.span "#{t('models.service_provider.schedule')}:", class: "label" %>
            <%= "#{@service_provider.schedule}" %>
        <% end %>
    <% end %>
    <%= tag.div class: "binome" do %>
        <%= content_tag :div, class: "field" do %>
            <%= tag.span t('models.service_provider.phone_number'), class: "label" %>
            <%= @service_provider.phone_number %>
        <% end %>
        <%= content_tag :div, class: "field" do %>
            <%= tag.span t('models.service_provider.email_address'), class: "label" %>
            <%= @service_provider.email_address %>
        <% end %>
    <% end %>
    <%= tag.div class: "field" do %>
        <%= content_tag :div do %>
            <%= tag.span t('models.service_provider.coordinate'), class: "label" %>
            <%= @service_provider.coordinate %>
        <% end %>
    <% end %>
<% end %>
<%= turbo_frame_tag "service-provider-services" do %>
    <%= tag.div class: "service-provider-services" do %>
        <% @service_provider.service_offers.each do |service_offer| %>
            <%= service_offer, can_request_quotes: true %>
        <% else %>
            <%= t('feedback.service_provider.no_service_offers') %>
        <% end %>
    <% end %>
<% end %>

app/views/service_providers/update.turbo_stream.erb
<%# return the form back to an info panel %>
<%= turbo_stream.update "#{dom_id(@service_provider)}-info" do %>
    <%= render partial: "service_providers/portal/info", locals: { service_provider: @service_provider } %>
<% end %>

<%# update the portal title in case the business name was changed %>
<%= turbo_stream.update "h1" do %>
    <%= @service_provider.name %>
<% end %>