config/routes.rb
Rails.application.routes.draw do
  # sign_up, sign_in, sign out, etc.
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resource :home, only: %i[ index ]

  # /service_providers
  resources :service_providers do
    resources :service_offers, controller: "service_providers/service_offers"
    resources :user_service_provider_accesses, as: :accesses
    resources :quote_requests, only: %i[ show index ]
    resource :quote_history, controller: "service_providers/quote_history", only: %i[ index ]
  end

  resources :service_quotes, only: %i[ new create destroy index ]
  resources :services, only: %i[ new create ]

  # /users
  resources :users do
    # users form actions #? turn into resource somehow?
    post :is_service_provider, on: :collection
    post :is_not_service_provider, on: :collection
  end

  resources :user_service_provider_accesses
  #?
  scope :user do
    get :service_providers, controller: :users, action: :service_providers, as: :user_service_providers
  end

  resources :service_requests do  # for when a client interacts with a service_request they have made
    collection do
      post :use_new_city, as: :use_new_city
      post :use_existing_city, as: :use_existing_city
    end
  end

  resource :service_request_coordinate_choice, only: %i[ new ]
  resource :service_form_cancellation, only: %i[ new ]

  resource :coordinate_city_choice, only: %i[ new ]

  # when service providers search for service requests that they might be able to fulfill
  resources :service_request_searches, only: %i[ new ]

  # there are many possible service providders for which a user might want to access their portals, so service provider portal is a plural resource
  resources :service_provider_portals, only: %i[ show ]
  # the client portal always redirects to the user's client account, so it is a singular resource
  resource :client_portal, only: [ :show ]

  # /clients
  resources :clients do
    resources :quote_requests, only: %i[ new create index ]
    resource :coordinate, only: %i[ new create edit update destroy ], controller: "clients/coordinates"
    resource :coordinate_edit_cancellation, only: %i[ new ], controller: "clients/coordinate_edit_cancellations"
=begin
    member do
      #! to be obsoleted x3
      get :edit_coordinate, to: "clients#edit_coordinate", as: :edit_coordinate
      get :cancel_edit_coordinate, to: "clients#cancel_edit_coordinate", as: :cancel_edit_coordinate
      patch :edit_coordinate, to: "clients#update_coordinate", as: :update_coordinate
    end
=end
  end

  namespace :client do
    resource :coordinate, only: %i[new create edit update destroy]
    resources :service_request_activations, only: %i[ new destroy ]
  end

  resources :service_provider_searches, only: %i[ new create ]

  #! to be obsoleted
  scope module: :clients do
    get "client/service_request/:id", to: "service_requests#show", as: :client_service_request
    get "client/service_request/:id/service_providers", to: "service_requests#find_providers", as: :find_service_request_providers
    post "client/service_request/:id/cancel", to: "service_requests#cancel", as: :cancel_service_request
    post "client/service_request/:id/activate", to: "service_requests#activate", as: :activate_service_request
  end

  # /service_providers
  scope :service_provider do
    get :browse_service_requests, to: "service_providers#browse_service_requests", as: :browse_service_requests_as_service_provider
    get :quote_history, to: "service_providers#quote_history", as: :service_provider_quote_history
  end

  # /cities
  resources :cities

  # /coordinates
  #! this probably shouldn't exist, should be through the other resources? or maybe only new/create
  resources :coordinates do
    # coordinate form actions
    # probably should use a resource, coordinate_city_choice or sth
    # /coordinates/use_new_city
    post :use_new_city, on: :collection
    # /coordinates/use_existing_city
    post :use_existing_city, on: :collection
  end

  # /service_categories
  resources :service_categories do
    member do
      # picker actions
      # todo how to turn into resource? => service_category_choice
      get :pick, as: :pick
    end
    # /service_categories/[:service_category_id]/services
    resources :services, only: %i[ index ]
  end

  # /transportation_services
  # todo
  # resources :transportation_services

  root "home#index"

  # Developement resources
  if Rails.env.development?
    resources :design_systems, only: [ :index ]
  end
end

app/controllers/user_service_provider_accesses_controller.rb
class UserServiceProviderAccessesController < ApplicationController
    before_action :authorize, only: %i[ index ]

    def index
        @accesses = current_user.user_service_provider_accesses.active
    end

    def new
        set_service_provider
        @user_service_provider_access = UserServiceProviderAccess.new(grantor_id: current_user.id, service_provider_id: @service_provider.id)
    end

    def edit
        set_user_service_provider_access
    end

    def create
        set_service_provider
        creator_result = UserServiceProviderAccesses::Creator.new(grantor: current_user).create(user_service_provider_access_params)

        if creator_result.created?
            @user_service_provider_access = creator_result.created
        else
            flash.alert = "Failed to create #{creator_result.created.inspect} with errors: #{creator_result.created.errors.full_messages}"
        end
    end

    def update
        set_user_service_provider_access
        @user_service_provider_access.update(user_service_provider_access_params)
    end

    def destroy
        set_user_service_provider_access
        @user_service_provider_access.destroy
    end

    private
    def set_service_provider
        @service_provider = ServiceProvider.find_by_id(params[:service_provider_id])
    end

    def set_user_service_provider_access
        @user_service_provider_access = UserServiceProviderAccess.find_by_id(params[:id])
    end

    def user_service_provider_access_params
        params.require(:user_service_provider_access).permit(:user_id, :user, :grantor_id, :service_provider_id, :user_role_id)
    end
end

app/helpers/user_service_provider_accesses_helper.rb
module UserServiceProviderAccessesHelper
end

app/views/user_service_provider_accesses/_fields.html.erb
<%# only allow to pick user if access doesn't already exist; must create a new one instead %>
<% if form.object.new_record? %>
    <%= form.field :user_id %>
<% end %>

<%= form.field :user_role, collection: UserRole.order(id: :asc), selected: 2 %>

<%= form.hidden_field :grantor_id %>
<%= form.hidden_field :service_provider_id %>

app/views/user_service_provider_accesses/_form.html.erb
<%= model_form_with model: user_service_provider_access do |form| %>
    <%= render partial: "user_service_provider_accesses/fields", locals: { form: form } %>
    <%= form.submit must_create?(user_service_provider_access) ? t('models.create') : t('models.update') %>
<% end %>

app/views/user_service_provider_accesses/_user_service_provider_access.html.erb
<%= tag.div class: "user-service-provider-access model-widget", id: dom_id(user_service_provider_access) do %>
    <%= tag.div user_service_provider_access.user.username, class: "user-service-provider-access__username" %>

    <%= tag.div user_service_provider_access.user_role.name, class: "user-service-provider-access__user-role" %>

    <%= tag.div currency(user_service_provider_access.user.email), class: "user-service-provider-access__email" %>

    <%= tag.div class: "actions" do %>
        <% if local_assigns[:can_edit] %>
            <%= model_edit_delete_actions service_provider_access_path(user_service_provider_access.service_provider, user_service_provider_access) %>
        <% end %>
    <% end %>
<% end %>

app/views/user_service_provider_accesses/create.turbo_stream.erb
<%# add created row to the list %>
<%= turbo_stream.append "user-service-provider-accesses" do %>
    <%# is_admin = true because it must be true to have gotten to this point %>
    <%= render "user_service_provider_accesses/user_service_provider_access", can_edit: true, user_service_provider_access: @user_service_provider_access %>
<% end %>
<%# clear the form %>
<%# todo have an option to create more so the form stays %>
<%= turbo_stream.update "user-service-provider-access-form" %>

app/views/user_service_provider_accesses/destroy.turbo_stream.erb
<%= turbo_stream.remove @user_service_provider_access %>

app/views/user_service_provider_accesses/edit.turbo_stream.erb
<%= turbo_stream.update "user-service-provider-access-form" do %>
    <%= render partial: "user_service_provider_accesses/form", locals: { user_service_provider_access: @user_service_provider_access } %>
<% end %>

app/views/user_service_provider_accesses/index.html.erb
<%= tag.section class: "menu", data: { test_id: "user-service-provider-accesses-menu" } do %>
    <% @accesses.each do |access| %>
        <%= link_to access.service_provider.name, service_provider_portal_path(access.service_provider), class: "button" %>
    <% end %>
<% end %>

app/views/user_service_provider_accesses/new.turbo_stream.erb
<%= turbo_stream.update "user-service-provider-access-form" do %>
    <%= render partial: "user_service_provider_accesses/form", locals: { user_service_provider_access: @user_service_provider_access } %>
<% end %>

app/views/user_service_provider_accesses/update.turbo_stream.erb
<%= turbo_stream.replace @user_service_provider_access do %>
    <%# is_admin = true because it must be true to have gotten to this point %>
    <%= render "user_service_provider_accesses/user_service_provider_access", can_edit: true, user_service_provider_access: @user_service_provider_access %>
<% end %>
<%# clear the form %>
<%= turbo_stream.update "user-service-provider-access-form" %>